import { Inter } from 'next/font/google'
import './globals.css'
import Provides from '@/store/Providers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'mindmap',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Provides>
          {children}
        </Provides>
      </body>
    </html>
  )
}
