import { Poppins } from 'next/font/google'
import './globals.scss'
import Provides from '@/store/Providers'
import { UserProvider } from '@auth0/nextjs-auth0/client';
const popins = Poppins({
  weight: '400',
  subsets: ['latin'],
})
export const metadata = {
  title: 'mindmap',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={popins.className}>
          <Provides>
            {children}
          </Provides>
        </body>
      </UserProvider>
    </html>
  )
}
