import { Inter } from 'next/font/google'
import './globals.css'
import Provides from '@/store/Providers'
import Header from '@/Components/Header/Header'
import Footer from '@/Components/Footer/Footer'
import { UserProvider } from '@auth0/nextjs-auth0/client';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'mindmap',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <UserProvider>
        <body className={inter.className}>
          {/* <Provides> */}
          <Header />
          {children}
          <Footer />
          {/* </Provides> */}
        </body>
      </UserProvider>
    </html>
  )
}
